spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/txoko_local_test?serverTimezone=UTC
    username: root
    password: txoko_local_test
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true

  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379